### ISSUE TITLE
CSS height-full scrolling ui issues

### ISSUE THREAD

**Issue by joseconstela** [github/personal-website#94]
I'm getting the same UI issue as #58 . Disabling the CSS rule for .height-full solves my problem. Tested on both latest Safari and Chrome on macOS Mojave 10.14.3

This is on https://joseconstela.com/ [repo](https://github.com/joseconstela/joseconstela.github.io) (using master branch forked on 9th March)

<img width="853" alt="Captura de pantalla 2019-03-10 a las 14 18 26" src="https://user-images.githubusercontent.com/6388629/54085520-62bc0280-433f-11e9-9485-6cb89f0adcbf.png">

With the rule disabled (via dev tools)

<img width="843" alt="Captura de pantalla 2019-03-10 a las 14 19 21" src="https://user-images.githubusercontent.com/6388629/54085534-82ebc180-433f-11e9-926b-0626a5cdd301.png">

cc @lucario

**Comment by lucario** [comment]
My guess is, it works on my site since I don't have more of an area to scroll, so it ends short, but since you have enough content for the need to scroll, it'll only go as far as your view height initially, rather than content length. For now you should remove my patch and commit it to your forks master to solve the issue, I am unsure about what to do for here, possible remove it completely, but doesn't solve the issue I was having.

**Comment by tsub** [comment]
For example, how about using `min-height: 100%` instead of `height: 100%`?

However, since there is no class for using `min-height: 100%` in primer, it is necessary to write the style directly.
https://github.com/primer/css/search?q=min-height&unscoped_q=min-height

**Comment by aadibajpai** [comment]
Yes, reverting #58 worked for me, full length sidebar works now even when scrolling.

**Comment by lucario** [comment]
@tsub If min height works for you, consider opening a pr here.

**Comment by tsub** [comment]
I opened a PR https://github.com/github/personal-website/pull/97 to fix it.
